export ZSH="/Users/ndhuynh/.oh-my-zsh"

plugins=(git)

source $ZSH/oh-my-zsh.sh

source /usr/local/opt/powerlevel9k/powerlevel9k.zsh-theme
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator host dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(background_jobs anaconda vcs)

alias htop="htop -d 1"
