# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH="/home/ndhuynh/.oh-my-zsh"
export TERM="xterm-256color"

# ZSH_THEME="powerlevel9k/powerlevel9k"
source /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator host dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(background_jobs anaconda vcs)

plugins=(git)

source $ZSH/oh-my-zsh.sh

alias htop="htop -d 1"

